# Generated by Django 3.0.3 on 2020-07-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ircbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('fbname', models.CharField(max_length=30)),
                ('lineid', models.CharField(max_length=30)),
                ('willing', models.CharField(max_length=5)),
                ('firsttime', models.CharField(max_length=5)),
            ],
        ),
    ]
