# Generated by Django 3.0.3 on 2020-07-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ircbot', '0002_registerform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='registerform',
            name='fbname',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='registerform',
            name='lineid',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='registerform',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
